{{- if .Values.websocket.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "upterm.fullname" . }}
  labels:
    {{- include "upterm.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.websocket.ingress_nginx_ingress_class }}
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/limit-connections: "4"
    nginx.ingress.kubernetes.io/limit-rps: "5"
    cert-manager.io/issuer: {{ include "upterm.fullname" . }}-letsencrypt
    {{- with .Values.websocket.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
    tls:
      - hosts:
        - {{ .Values.hostname }}
        secretName: {{ .Values.hostname | replace "." "-" }}-tls
    rules:
      - host: {{ .Values.hostname }}
        http:
          paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "upterm.fullname" . }}
                port:
                  number: 80
{{- end }}
